### ISSUE TITLE
老哥 这个报错是怎么回事呢？

### ISSUE THREAD

**Issue by xiaxichen** [pengchujin/v2rayDocker#2]
<img width="738" alt="屏幕快照 2019-06-08 下午2 53 20" src="https://user-images.githubusercontent.com/34499404/59143411-670ac100-89fd-11e9-82ce-f09ec21440da.png">

**Comment by pengchujin** [comment]
你域名解析 对的？

**Comment by leoatchina** [comment]
请问下是一定要域名解析过去，不能直接用ip吗？

**Comment by pengchujin** [comment]
> 请问下是一定要域名解析过去，不能直接用ip吗？

肯定不可以啊,没域名怎么签发证书....走TLS

**Comment by leoatchina** [comment]
> > 请问下是一定要域名解析过去，不能直接用ip吗？
> 
> 肯定不可以啊,没域名怎么签发证书....走TLS

搞定，  33元买了10年的纯数字域名+gcloud+你的docker

**Comment by xiaxichen** [comment]
ok、解决了！
