### ISSUE TITLE
what error is this

### ISSUE THREAD

**Issue by rsoorajs** [pengchujin/v2rayDocker#34]
![IMG_20210104_162729_079](https://user-images.githubusercontent.com/20116017/103528332-c535a980-4ea9-11eb-8551-84e654de5b5f.jpg)

Where to add domain.i am using https://uffizzi.com to host the vpn..so icant execute  `docker run.....` command..so i want to pre add my domain..so kindly tell me,where i have to add my domain,before deploying..

Thanks in advance

**Comment by shalahu** [comment]
`sudo docker run -d --rm --name v2ray -p 443:443 -p 80:80 -v $HOME/.caddy:/root/.caddy  pengchujin/v2ray_ws:0.11 YOURDOMAIN.COM V2RAY_WS && sleep 3s && sudo docker logs v2ray`

Replace YOURDOMAIN.COM with your own domain.
