### ISSUE TITLE
脚本存在安全问题

### ISSUE THREAD

**Issue by ryanInf** [pengchujin/v2rayDocker#37]
存在严重的信息泄露问题，可能导致v2ray配置泄露
可以通过访问web获取v2ray配置文件
https://x.x.x.x.com/caddy.log
https://x.x.x.x.com/sebs.js
https://x.x.x.x.com/v2ray.js

其中sebs.js就包含了v2ray的连接信息，泄露后可让人连接上v2ray

建议：
屏蔽非web文件的访问

版本：pengchujin/v2ray_ws:0.08（如已修复请忽略）

**Comment by shalahu** [comment]
Caddyfile 增加如下配置即可

rewrite {
  if_op or
  if {file} ends_with .js
  if {file} ends_with .log
  to /404
  }

参看修复：https://github.com/shalahu/v2rayDocker/
