### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by hexiaoyanh** [pengchujin/v2rayDocker#39]
2021/05/28 09:45:50 [ERROR] failed to copy buffer:  read tcp 127.0.0.1:37920->127.0.0.1:2333: use of closed network connection
2021/05/28 09:45:51 [ERROR] failed to copy buffer:  read tcp 127.0.0.1:37922->127.0.0.1:2333: use of closed network connection
2021/05/28 09:45:51 [ERROR] failed to copy buffer:  read tcp 127.0.0.1:37924->127.0.0.1:2333: use of closed network connection
2021/05/28 09:45:52 [ERROR] failed to copy buffer:  read tcp 127.0.0.1:37930->127.0.0.1:2333: use of closed network connection
2021/05/28 09:45:53 [ERROR] failed to copy buffer:  read tcp 127.0.0.1:37932->127.0.0.1:2333: use of closed network connection

**Comment by hexiaoyanh** [comment]
在v2rayng中能ping通，但无法使用

**Comment by kenshinji** [comment]
似乎是caddy的问题 https://github.com/caddyserver/caddy/issues/2783
