### ISSUE TITLE
谢谢你的docker，实测能用

### ISSUE THREAD

**Issue by ntgeralt** [pengchujin/v2rayDocker#4]
另外请教一下，如果想让其重启时容器自启动后uuid不变，应该怎么做。

另外有两点微小建议
样例的 sebs.club写成yourdomain.com可以明显一些；
样例启动时提示Unable to find image 'pengchujin/v2ray_ws:latest' locally；不影响使用
dockerfile里的ARG version="0.11.1"我这里build不出来，改成1.0.1解决；
and there is no need to show 'Your v2ray started' :)

**Comment by pengchujin** [comment]
好的 非常感謝，我看下 儘快修改你說的問題。

**Comment by pengchujin** [comment]
已更新，uuid 可以自定义了。
 sebs.club 也写成 yourdomain.com 了。
“Unable to find image 'pengchujin/v2ray_ws:latest' locally” 这个不是问题是 docker 本地没有次镜像。
“dockerfile里的ARG ” 这个问题暂不确定。

**Comment by ntgeralt** [comment]
感谢
