### ISSUE TITLE
怎样修改caddy首页内容？

### ISSUE THREAD

**Issue by k3179** [pengchujin/v2rayDocker#5]
怎样修改caddy首页内容？

**Comment by pengchujin** [comment]
不能通过 Docker 直接定义，不过你可以修改 Dockerfile 下面的 index.html

**Comment by meotao** [comment]
和楼主相同的问题，搜索了没找到修改修改的方法，能否出一个简单的修改步骤，谢谢

**Comment by k3179** [comment]
> 不能通过 Docker 直接定义，不过你可以修改 Dockerfile 下面的 index.html

这个具体怎么操作呢？

**Comment by test0103** [comment]
> 和楼主相同的问题，搜索了没找到修改修改的方法，能否出一个简单的修改步骤，谢谢

可以在运行docker后，使用docker exec -it containerID bash 进入容器，在使用vi来修改html文件

**Comment by k3179** [comment]
谢谢
